Fix a compilation error
 Compilation gave the following error:

 Line 61:11:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 83:11:  Expected an assignment or function call and instead saw an expression  no-unused-expressions

  This was due to a comma instead of a semicolon at the end of the assignments on these lines.